import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:permission_handler/permission_handler.dart';

class Checksuper {
  static const MethodChannel _channel = const MethodChannel('checksuper');

  static Future<bool> isDeviceRooted() async {
    final bool isRooted = await _channel.invokeMethod('checkRoot');
    return isRooted;
  }
}

Future<bool> checkIfSuperUser() async {
  print("[Root Check]: Started");
  print('isReleaseMode: $kReleaseMode');
  bool isRooted = false;
  if (kReleaseMode) {
    isRooted = await Checksuper.isDeviceRooted();
  }
  print("[Root Check]: Result - ${isRooted.toString()}");
  return isRooted;
}

String getNumberWithPrefixZero(int number) {
  return number.toString().length <= 1
      ? "0" + number.toString()
      : number.toString();
}

Future<void> requestGallery() async {
  if (Platform.isIOS) await requestPhotos();
  if (Platform.isAndroid) await requestStorage();
}

Future<void> requestPhotos() async {
  if (Platform.isAndroid) return null;
  await Permission.photos.request();
}

Future<void> requestStorage() async {
  await Permission.storage.request();
}

List<String> lebaneseTowns() {
  return [
    "Aaba",
    "Aadloun",
    "Aarjes",
    "Aaytit",
    "Abbassieh",
    "Abdine",
    "Abey",
    "Ablah",
    "Abra",
    "Achqout",
    "Adayseh",
    "Adchit",
    "Adonis",
    "Adousieh",
    "Afqa",
    "Afsaddik",
    "Aghmid",
    "Ain",
    "Ain Arab",
    "Ain Ata",
    "Ain Baal",
    "Ain Dara",
    "Ain Ebel",
    "Ain Ekrine",
    "Ain El Delb",
    "Ain Harcha",
    "Ain Jedideh",
    "Ain Jrain",
    "Ain Kani",
    "Ain Kanya",
    "Ain Kfarzabad",
    "Ain Ksour",
    "Ain Onoub",
    "Ain Qana",
    "Ain Wzein",
    "Ain Zebdeh",
    "Ain Zhalta",
    "Ain el Remmaneh",
    "Ain el Rihaneh",
    "Ain el Saydeh",
    "Ain el Tineh",
    "Ain el-Ghouaybeh",
    "Ain trez",
    "Ainab",
    "Ainata",
    "Ainbal",
    "Aintoura",
    "Aintourine",
    "Aitanite",
    "Aitou",
    "Aitouleh",
    "Ajaltoun",
    "Ajdabra",
    "Ajed Ibrine",
    "Akabeh",
    "Akaybeh",
    "Akoura",
    "Akroum",
    "Al Rihan",
    "Al-Qalamoun",
    "Al-Rafid",
    "Aley",
    "Ali el Nahri",
    "Alma",
    "Alma el Chaab",
    "Almat el-Chemalieh",
    "Almat el-Janubieh",
    "Amioun",
    "Ammatour",
    "Ammik",
    "Amsheet",
    "Ana",
    "Andaket",
    "Anfeh",
    "Anout",
    "Anqoun",
    "Ansar",
    "Arab Ellahib",
    "Arabsalim",
    "Aramoun",
    "Aramoun el Ghareb",
    "Aramta",
    "Aray",
    "Arbet Kozhaya",
    "Ardeh",
    "Arnoun",
    "Arqa",
    "Arsal",
    "Arzoun",
    "As-Sultaniyah",
    "Asoun",
    "Assia",
    "Atrine",
    "Aychieh",
    "Ayha",
    "Aynata",
    "Ayta el Chaeb",
    "Ayta el Fekhar",
    "Ayta el Jabal",
    "Aytaroun",
    "Azour",
    "Azra & Ozor",
    "Baakline",
    "Baalbek",
    "Baaloul",
    "Baasir",
    "Baatharan",
    "Baawerta",
    "Bab Mareh",
    "Bablieh",
    "Badghan",
    "Baflaya",
    "Baissour",
    "Bakhoun",
    "Bakifa",
    "Ballouneh",
    "Bani Hayann",
    "Bar Elias",
    "Barhelyoun",
    "Barich",
    "Barja",
    "Barka",
    "Barouk",
    "Barsa",
    "Barti",
    "Basloukit",
    "Bassatine",
    "Bater",
    "Batha",
    "Batloun",
    "Batoulieh",
    "Batroumine",
    "Batroun",
    "Bayssarieh",
    "Bayyad",
    "Bazooun",
    "Bazourieh",
    "Bchaaleh",
    "Bchamoun",
    "Bchetfine",
    "Bdadoun",
    "Bdebba",
    "Beba",
    "Bebnine",
    "Bechealeh",
    "Bechmezzine",
    "Bechouat",
    "Bechtlida - Fidar",
    "Beddawi - Wadi Nahe",
    "Bednayel",
    "Bednayel",
    "Bedyass",
    "Beino",
    "Beit Lahia",
    "Beit Lif",
    "Beit Mounzer",
    "Beit Yahoun",
    "Beit el Fokss",
    "Beiteddine",
    "Bejjeh",
    "Bekaasafrine",
    "Bekaatat Achkout",
    "Bekhaaz",
    "Bekka",
    "Bemkine",
    "Bennieh",
    "Benweteh",
    "Berbara",
    "Berjein & Mreyjat",
    "Berkayel",
    "Bezhel & Mradyeh",
    "Bhairet Toula",
    "Bhamdoun el Balda",
    "Bhamdoun el Mhatta",
    "Bhannine & Artousa",
    "Bint Jbeil",
    "Bireh",
    "Bisri",
    "Bkaakafra",
    "Bkarsouna",
    "Bkassine",
    "Bkeftine",
    "Bkerkacha",
    "Bkesmaya",
    "Bkhechtey",
    "Bkosta",
    "Blat",
    "Blawza",
    "Bleibel",
    "Blida",
    "Bmahray",
    "Bnaafoul",
    "Bnachii",
    "Bodai",
    "Borj Kalaway",
    "Borj Rahal",
    "Borj el Chamali",
    "Boslaya",
    "Botme",
    "Bouar",
    "Bouarej",
    "Bourghlieh",
    "Bourj El-Moulouk",
    "Boustane",
    "Bqaatouta",
    "Braachit",
    "Braissat",
    "Bramieh",
    "Breykaah",
    "Brih",
    "Brital",
    "Bsaba",
    "Bsarma",
    "Bserrine",
    "Bsharri",
    "Bsouss",
    "Btadhi",
    "Btalloun",
    "Btater",
    "Bteddine el Lekech",
    "Btermaz",
    "Bterram",
    "Btouratij",
    "Byblos",
    "Bziza",
    "Chaat",
    "Chadra",
    "Chahtoul & Jouret Mehad",
    "Chakra wa Doubeih",
    "Chameh",
    "Chanay",
    "Charkiyeh",
    "Charoun",
    "Chartoun",
    "Chawaghir el Fawka Wal Tahta",
    "Chebtine",
    "Chehabie",
    "Chehour",
    "Cheikh Mohammad",
    "Chekka",
    "Chemlan",
    "Chihine",
    "Chlifa",
    "Chmestar",
    "Chmout",
    "Chnaniir",
    "Choueifat",
    "Choukine",
    "Chtaura",
    "Chwayya",
    "Daher el Ahmar",
    "Dahr El Maghara",
    "Dalhoun",
    "Damour",
    "Dar Beechtar",
    "Dar Chmezzine",
    "Harissa",
    "Daraya",
    "Dareb el Sim",
    "Dawra",
    "Debaal",
    "Debbine",
    "Debel",
    "Deddeh",
    "Deir Amess",
    "Deir Ammar",
    "Deir Antar",
    "Deir Dourit",
    "Deir El Aachayer",
    "Deir Kanoun",
    "Deir Koubel",
    "Deir Kouche",
    "Deir Mimas",
    "Deir Nbouh",
    "Deir Syriane",
    "Deir el Ahmar",
    "Deir el Ghazal",
    "Deir el Qamar",
    "Deir el Zahrani",
    "Denbo",
    "Derdghaya",
    "Dfoun",
    "Dibbiyeh",
    "Dimane",
    "Dlebta",
    "Dmit",
    "Doueir",
    "Douma",
    "Douriss",
    "Ebba",
    "Ebel El Saqi",
    "Eddeh",
    "Ehden",
    "Ehmej",
    "Eitat",
    "Ejbeh",
    "Erkay",
    "Faitroun",
    "Fakiha",
    "Faraya",
    "Fardiss",
    "Fatqa",
    "Fatreh",
    "Ferzol",
    "Fghal",
    "Fih",
    "Fleweh",
    "Fouara",
    "Froun",
    "Ghalboun",
    "Ghandouriyeh",
    "Gharife",
    "Gharzouz",
    "Ghaza",
    "Ghazieh",
    "Ghazir",
    "Ghbaleh",
    "Ghedrass",
    "Ghessanieh",
    "Ghosta",
    "Ghyneh",
    "Habbouch",
    "Hadath Baalbek",
    "Hadath El Jebbeh",
    "Hadchit",
    "Halat",
    "Halba",
    "Halloussieh",
    "Hamat",
    "Hanawey",
    "Hanine",
    "Haql El Aazime",
    "Harbata",
    "Hardine",
    "Haref",
    "Haret Al Fawar",
    "Haret Jandal",
    "Haret Saida",
    "Harouf",
    "Hasbaya",
    "Hasroun",
    "Hasrout",
    "Hay el Fikany",
    "Haytoura",
    "Hbariyeh",
    "Hboub",
    "Hdatha",
    "Henniye",
    "Heri",
    "Hermel",
    "Hezerta",
    "Hisah",
    "Hiyata",
    "Hizzine",
    "Hjoula",
    "Hlabta",
    "Hlalyeh",
    "Hmayri",
    "Hoch",
    "Hoch Harimeh",
    "Anjar",
    "Homsiyeh",
    "Hosein",
    "Hosh Barada",
    "Hosh Snid",
    "Hosh Tal Safiya",
    "Hosh el Rafika",
    "Hosrayel",
    "Houla",
    "Houmal",
    "Houmin el Fawka",
    "Houmin el Tahta",
    "Hrajel",
    "Hsoun",
    "Iaal",
    "Iaat",
    "Ibrine",
    "Insariat",
    "Irzay",
    "Jabbouleh",
    "Jadra",
    "Jahlieh",
    "Jaj",
    "Janneh",
    "Janta",
    "Jarjouh",
    "Jarmak",
    "Jdaideh",
    "Jdita",
    "Jeb Jennine",
    "Jebbine",
    "Jebchit",
    "Jeddayel",
    "Jeita",
    "Jernaya",
    "Jezzine",
    "Jiyeh",
    "Jmeyjmeh",
    "Jouar el Hachich",
    "Jouaya",
    "Joun",
    "Jounieh",
    "Jouret Termos",
    "Kaah el Rim",
    "Kaakaiyat el Snaoubar",
    "Kaakaiyet el Jisr",
    "Kab Elias",
    "Kabrikha",
    "Kafarkela",
    "Kafra",
    "Kaftoun",
    "Kahlouniye",
    "Kalaway",
    "Kamed el Laouz",
    "Kana",
    "Kantara",
    "Karahbache",
    "Karaoun",
    "Karkha",
    "Karm el Moher",
    "Karmsaddeh",
    "Kasarnaba",
    "Kasser",
    "Kattine",
    "Kawkaba",
    "Kawthariyet el Siyyad",
    "Kawzah",
    "Kefraya",
    "Kehaleh",
    "Kelhat",
    "Ketermaya",
    "Keyfoun",
    "Kfar Abida",
    "Kfar Baal",
    "Kfar Danis",
    "Kfar Matta",
    "Kfar Mechki",
    "Kfar Nabrakh",
    "Kfar Helda",
    "Kfaraamey",
    "Kfarakka",
    "Kfarchalane",
    "Kfarchouba",
    "Kfardebian",
    "Kfardlakos",
    "Kfardounine",
    "Kfarfakoud",
    "Kfarfalous",
    "Kfarfila",
    "Kfarfou",
    "Kfarfouk",
    "Kfarhabou",
    "Kfarhamam",
    "Kfarhata",
    "Kfarhay",
    "Kfarhazir",
    "Kfarhim",
    "Kfarhouna",
    "Kfarjarrah",
    "Kfarkahel",
    "Kfarkatra",
    "Kfarmilke",
    "Kfarniss",
    "Kfarremane",
    "Kfarsaroun",
    "Kfarsghab",
    "Kfarshakhna",
    "Kfarsir",
    "Kfartebnit",
    "Kfaryachit",
    "Kfarzabad",
    "Kfarzeina",
    "Kfeir",
    "Kfour",
    "Khalwat",
    "Khartoum",
    "Kherbet Rouha",
    "Khiam",
    "Khirbet Selm",
    "Khodr",
    "Khraybeh",
    "Khrayeb",
    "Kifraya",
    "Klayaa",
    "Kleiat",
    "Knayse",
    "Kobayat",
    "Kolayleh",
    "Kommatyeh",
    "Kosba",
    "Kossaybeh",
    "Kouakh",
    "Kounine",
    "Kousaya",
    "Krayeh",
    "Labweh",
    "Laqlouq",
    "Lassa",
    "Lebaa",
    "Lebbaya",
    "Lehfed",
    "Louaizeh",
    "Loubieh",
    "Maad",
    "Maarake",
    "Maaroub",
    "Maasser Beiteddine",
    "Maasser el Chouf",
    "Maaysra",
    "Machen",
    "Machghara",
    "Machmouche",
    "Maghdouché",
    "Mahroune",
    "Majadel",
    "Majdalzoun",
    "Majdel Balhiss",
    "Majdel Selem",
    "Majdelbaana",
    "Majdelyoun",
    "Majdloun",
    "Maknounieh",
    "Manara",
    "Mansouri",
    "Mansourieh",
    "Marj",
    "Marj el Zhour",
    "Markaba",
    "Maroun el Ras",
    "Marwahin",
    "Masaoudiyeh",
    "Mastita",
    "Maydoun",
    "Mayfadoun",
    "Qottara",
    "Mayrouba",
    "Mays el Jabal",
    "Mazboud",
    "Mazraat Al Toufah",
    "Mazraat Mechref",
    "Mazraat el Chouf",
    "Mazraat el Daher",
    "Mazraat es-Siyad",
    "Mdoukha",
    "Mechref",
    "Meemarieh",
    "Majdal",
    "Merouaniyeh",
    "Metrit",
    "Mghayreh",
    "Mhaydseh",
    "Midan",
    "Mina",
    "Minyara",
    "Minyeh",
    "Kadrieh",
    "Miyeh w Miyeh",
    "Miziara",
    "Mjaydel",
    "Mlikh",
    "Moukhtara",
    "Mrah Sraj",
    "Mrayjat",
    "Mristeh",
    "Naameh",
    "Nabatieh el Fawka",
    "Nabatieh el Tahta",
    "Nabi Ayla",
    "Nabi Chit",
    "Nabi Othman",
    "Nahr Ibrahim",
    "Najjarieh",
    "Nakhleh",
    "Nakoura",
    "Namiriyeh",
    "Nemrine & Bkaouza",
    "Niha",
    "Oqayba",
    "Qaa",
    "Qarha",
    "Qartaba",
    "Qnat",
    "Qnaywer",
    "Raachine",
    "Rab Thalathine",
    "Rachaya el Fokhar",
    "Rachiine",
    "Rahbe",
    "Rmayleh",
    "Ramadiye",
    "Ramlieh",
    "Ramyah",
    "Ras Baalbek",
    "Ras Nahhache",
    "Ras Osta",
    "Rashaya",
    "Raskifa",
    "Rasmaska",
    "Rayfoun",
    "Rchaf",
    "Rechdebbine",
    "Rechknanay",
    "Rechmaya",
    "Remhala",
    "Rhit",
    "Rihaneh",
    "Rimat",
    "Riyak",
    "Rmeich",
    "Rmeileh",
    "Rouaysset el Neeman",
    "Roum",
    "Roumine",
    "Saadnayel",
    "Saayde",
    "Sabbah",
    "Safra",
    "Saghbine",
    "Saksakieh",
    "Salhieh",
    "Saoufar",
    "Sarafand",
    "Sarba",
    "Sawaneh",
    "Sawiri",
    "Saydoun",
    "Sebline",
    "Sehayleh",
    "Selaata",
    "Selha",
    "Semkanieh",
    "Serbine",
    "Serhel",
    "Seriine el Fawka",
    "Seriine el Tahta",
    "Serjbel",
    "Sfaray",
    "Sfireh",
    "Shebaa",
    "Shheem",
    "Siddikine",
    "Sidon",
    "Sir el Gharbiyeh",
    "Sohmor",
    "Sojod",
    "Souk el Ghareb",
    "Srifa",
    "Sultan Yaakoub",
    "Taalabaya",
    "Taanayel",
    "Taazanieh",
    "Tabarja",
    "Tafahta",
    "Tallousseh",
    "Talya",
    "Tanbourit",
    "Tannoura",
    "Tannourine",
    "Tarane",
    "Taraya",
    "Tartej",
    "Tayrdebba",
    "Tayrfelsay",
    "Tayrharfa",
    "Tebnine",
    "Temnin el Fawka",
    "Temnin el Tahta",
    "Terbol",
    "Toula",
    "Toura",
    "Tourza",
    "Tripoli",
    "Tyre",
    "Wadi El Laymoun",
    "Wadi Faara",
    "Wadi Jezzine",
    "Warhanieh",
    "Wazzany",
    "Werdanieh",
    "Yahchouch",
    "Yammouneh",
    "Yanouh",
    "Yanta",
    "Yarine",
    "Yaroun",
    "Yater",
    "Yehmor",
    "Younine",
    "Zaarourieh",
    "Zaaytre",
    "Zaghdraiya",
    "Zahlé",
    "Zakroun",
    "Zan",
    "Zawtar el Charkiyeh",
    "Zawtar el Gharbiyeh",
    "Zebdine",
    "Zefta",
    "Zeita",
    "Zgharta",
    "Zibkin",
    "Zouk Mikael",
    "Zouk Mosbeh",
    "Zrarieh",
  ];
}
